import type { InboxThread, ThreadDetail } from './inbox-types'
import { PORTAL_CLOCK_FIXTURE_PATHS } from '@/lib/portal-clock-fixture'

const GUEST_WIFI_DRAFT = 'Hi Alex — wifi details are in the guest portal.'

export const FIXTURE_THREADS: InboxThread[] = [
  {
    id: 1,
    threadKind: 'booking',
    bookingId: 101,
    bookerName: 'Alex Guest',
    suite: 'Cottage A',
    checkIn: '2026-10-01',
    checkOut: '2026-10-04',
    nightsbridgeBookingId: 'NB-4401',
    lastChannel: 'whatsapp_web',
    lastInboundChannel: 'whatsapp_web',
    lastMessageAt: '2026-09-24T16:10:00.000Z',
    preview: GUEST_WIFI_DRAFT,
    pendingReply: true,
    hasOpenDraft: true,
    needsAttention: true,
    sortBucket: 0,
    hygieneStatus: null,
    fromNumber: 'alex.guest.with.a.long.local-part@example.invalid',
  },
  {
    id: 2,
    threadKind: 'booking',
    bookingId: 102,
    bookerName: 'Jordan Booker',
    suite: 'Falcon Suite',
    checkIn: '2026-10-12',
    checkOut: '2026-10-14',
    nightsbridgeBookingId: 'NB-4402',
    lastChannel: 'email',
    lastInboundChannel: 'email',
    lastMessageAt: '2026-09-23T09:00:00.000Z',
    preview: 'Can we add a late checkout if the suite is free?',
    pendingReply: false,
    hasOpenDraft: false,
    needsAttention: false,
    sortBucket: 2,
    hygieneStatus: null,
    fromNumber: 'jordan.booker@example.invalid',
  },
  {
    id: 3,
    threadKind: 'temp',
    bookingId: null,
    bookerName: 'Unmatched Number',
    suite: null,
    checkIn: null,
    checkOut: null,
    nightsbridgeBookingId: null,
    lastChannel: 'sms',
    lastInboundChannel: 'sms',
    lastMessageAt: '2026-09-22T18:00:00.000Z',
    preview: 'Hi, this is a fixture unmatched SMS for layout wrap checks.',
    pendingReply: true,
    hasOpenDraft: false,
    needsAttention: true,
    sortBucket: 1,
    hygieneStatus: 'nudged',
    fromNumber: '+15555550123',
  },
]

export const FIXTURE_DETAILS: Record<number, ThreadDetail> = {
  1: {
    id: 1,
    threadKind: 'booking',
    bookingId: 101,
    bookerName: 'Alex Guest',
    suite: 'Cottage A',
    checkIn: '2026-10-01',
    checkOut: '2026-10-04',
    nightsbridgeBookingId: 'NB-4401',
    lastChannel: 'whatsapp_web',
    lastInboundChannel: 'whatsapp_web',
    defaultOutboundChannel: 'whatsapp_web',
    fromNumber: 'alex.guest.with.a.long.local-part@example.invalid',
    status: 'open',
    hygieneStatus: null,
    openDraft: {
      text: GUEST_WIFI_DRAFT,
      source: 'heuristic',
      kind: 'reply',
    },
    linkCandidates: [],
    messages: [
      {
        id: 11,
        direction: 'inbound',
        channel: 'whatsapp_web',
        body: `Please confirm wifi for Cottage A. Portal: ${PORTAL_CLOCK_FIXTURE_PATHS['fixture-pre']}`,
        timestamp: '2026-09-24T16:10:00.000Z',
        isSpam: false,
      },
      {
        id: 12,
        direction: 'outbound',
        channel: 'email',
        senderAddress: 'stay@example.invalid',
        body: 'Earlier note sent to alex.guest.with.a.long.local-part@example.invalid',
        timestamp: '2026-09-23T08:00:00.000Z',
        isSpam: false,
      },
      {
        id: 13,
        direction: 'outbound',
        channel: 'whatsapp',
        body: GUEST_WIFI_DRAFT,
        timestamp: '2026-09-24T16:12:00.000Z',
        isSpam: false,
        deliveryStatus: 'pending',
        draftReply: GUEST_WIFI_DRAFT,
        status: 'drafted',
      },
    ],
  },
  2: {
    id: 2,
    threadKind: 'booking',
    bookingId: 102,
    bookerName: 'Jordan Booker',
    suite: 'Falcon Suite',
    checkIn: '2026-10-12',
    checkOut: '2026-10-14',
    nightsbridgeBookingId: 'NB-4402',
    lastChannel: 'email',
    lastInboundChannel: 'email',
    defaultOutboundChannel: 'email',
    fromNumber: 'jordan.booker@example.invalid',
    status: 'open',
    hygieneStatus: null,
    openDraft: null,
    linkCandidates: [],
    messages: [
      {
        id: 21,
        direction: 'inbound',
        channel: 'email',
        senderAddress: 'jordan.booker@example.invalid',
        body: 'Can we add a late checkout if the suite is free?',
        timestamp: '2026-09-23T09:00:00.000Z',
        isSpam: false,
      },
    ],
  },
  3: {
    id: 3,
    threadKind: 'temp',
    bookingId: null,
    bookerName: 'Unmatched Number',
    suite: null,
    checkIn: null,
    checkOut: null,
    nightsbridgeBookingId: null,
    lastChannel: 'sms',
    lastInboundChannel: 'sms',
    defaultOutboundChannel: 'sms',
    fromNumber: '+15555550123',
    status: 'open',
    hygieneStatus: 'nudged',
    openDraft: null,
    linkCandidates: [
      {
        id: 101,
        guestName: 'Alex Guest',
        checkIn: '2026-10-01',
        checkOut: '2026-10-04',
        suite: 'Cottage A',
      },
    ],
    messages: [
      {
        id: 31,
        direction: 'inbound',
        channel: 'sms',
        body: 'Hi, this is a fixture unmatched SMS for layout wrap checks.',
        timestamp: '2026-09-22T18:00:00.000Z',
        isSpam: false,
      },
    ],
  },
}
