import { NextRequest, NextResponse } from 'next/server'

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { booking, quote, format = 'markdown' } = body

    if (!booking || !quote) {
      return NextResponse.json(
        { error: 'Missing booking or quote data' },
        { status: 400 }
      )
    }

    const markdown = generateMarkdownQuote(booking, quote)

    if (format === 'html') {
      const html = markdownToSimpleHTML(markdown)
      return new NextResponse(html, {
        status: 200,
        headers: {
          'Content-Type': 'text/html',
          'Content-Disposition': `attachment; filename="quote-${booking.property.replace(/\s+/g, '-')}.html"`
        }
      })
    }

    return new NextResponse(markdown, {
      status: 200,
      headers: {
        'Content-Type': 'text/markdown',
        'Content-Disposition': `attachment; filename="quote-${booking.property.replace(/\s+/g, '-')}.md"`
      }
    })
  } catch (error) {
    console.error('Quote export error:', error)
    return NextResponse.json(
      { error: 'Failed to generate quote export' },
      { status: 500 }
    )
  }
}

function generateMarkdownQuote(booking: any, quote: any): string {
  const today = new Date().toLocaleDateString('en-ZA', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  })

  return `# Quote for ${booking.guestName}

**Property:** ${booking.property}  
**Quote Date:** ${today}  
**Status:** DRAFT - Requires Approval

---

## Booking Details

- **Guest Name:** ${booking.guestName}
- **Check-in:** ${booking.checkIn}
- **Check-out:** ${booking.checkOut}
- **Number of Nights:** ${booking.nights}
- **Accommodation:** ${booking.room}

---

## Pricing

| Item | Amount |
|------|--------|
| ${booking.nights} nights × Rate | ${quote.ratePerNight} |
| Subtotal | ${quote.subtotal} |
| Tax (15%) | ${quote.tax} |
| **Total** | **${quote.total}** |

${quote.note ? `\n> **Note:** ${quote.note}\n` : ''}

---

## Important Information

⚠️ **This quote is DRAFT ONLY and requires approval before sending to guest.**

✅ **Hard Gates:**
- All rates from uploaded rate card only
- No invented pricing
- Requires H7 approval gate before send
- Draft-only until approved by property owner

---

## Next Steps

1. Review pricing accuracy
2. Obtain H7 approval from property owner
3. Send quote to guest via approved channel
4. Request deposit confirmation
5. Generate welcome pack upon booking confirmation

---

*Generated by GuestFlow SaaS - Demo Version*  
*Quote ref: DRAFT-${Date.now()}*
`
}

function markdownToSimpleHTML(markdown: string): string {
  let html = markdown
    .replace(/^# (.*$)/gim, '<h1>$1</h1>')
    .replace(/^## (.*$)/gim, '<h2>$1</h2>')
    .replace(/^### (.*$)/gim, '<h3>$1</h3>')
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.*?)\*/g, '<em>$1</em>')
    .replace(/^> (.*$)/gim, '<blockquote>$1</blockquote>')
    .replace(/^- (.*$)/gim, '<li>$1</li>')
    .replace(/\n\n/g, '</p><p>')
    .replace(/\n/g, '<br>')

  // Wrap list items in ul
  html = html.replace(/(<li>.*?<\/li>)(?!<li>)/gs, '<ul>$1</ul>')

  // Basic table conversion
  html = html.replace(/\|(.*?)\|/g, (match) => {
    return match.split('|').filter(cell => cell.trim()).map(cell => 
      `<td>${cell.trim()}</td>`
    ).join('')
  })
  html = html.replace(/(<td>.*?<\/td>)+/g, '<tr>$&</tr>')
  html = html.replace(/(<tr>.*?<\/tr>)+/gs, '<table border="1" cellpadding="8" style="border-collapse: collapse; margin: 20px 0;">$&</table>')

  return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quote - GuestFlow</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            line-height: 1.6;
            max-width: 800px;
            margin: 40px auto;
            padding: 20px;
            color: #333;
        }
        h1 { color: #2563eb; margin-bottom: 0.5em; }
        h2 { color: #1e40af; margin-top: 2em; border-bottom: 2px solid #e5e7eb; padding-bottom: 0.3em; }
        h3 { color: #1e3a8a; }
        table { width: 100%; margin: 1em 0; }
        th, td { padding: 0.75em; text-align: left; }
        th { background-color: #f3f4f6; font-weight: 600; }
        blockquote { 
            background-color: #dbeafe; 
            border-left: 4px solid #2563eb; 
            padding: 1em; 
            margin: 1em 0;
        }
        hr { border: none; border-top: 1px solid #e5e7eb; margin: 2em 0; }
        @media print {
            body { margin: 0; padding: 20px; }
        }
    </style>
</head>
<body>
    <p>${html}</p>
</body>
</html>`
}
