import * as fs from 'fs';
import * as path from 'path';
import { ValidationReport } from './types.js';

/**
 * Generate markdown report from validation results
 */
export function generateMarkdownReport(report: ValidationReport): string {
  const lines: string[] = [];
  
  lines.push('# Suno Job Package Validation Report');
  lines.push('');
  lines.push(`**Validated:** ${report.timestamp}`);
  lines.push(`**Job Directory:** \`${report.job_dir}\``);
  lines.push('');
  
  lines.push('## Summary');
  lines.push('');
  lines.push(`- **Total Checks:** ${report.summary.total_checks}`);
  lines.push(`- **Passed:** ${report.summary.passed}`);
  lines.push(`- **Failed:** ${report.summary.failed}`);
  lines.push(`- **Overall:** ${report.summary.all_passed ? '✅ PASS' : '❌ FAIL'}`);
  lines.push('');
  
  lines.push('## Validation Checks');
  lines.push('');
  
  let checkNumber = 1;
  
  for (const [key, check] of Object.entries(report.checks)) {
    const status = check.passed ? '✅ PASS' : '❌ FAIL';
    const title = key.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
    
    lines.push(`### ${checkNumber}. ${title}`);
    lines.push('');
    lines.push(`**Status:** ${status}`);
    lines.push(`**Message:** ${check.message}`);
    
    if (check.details) {
      lines.push('');
      lines.push(`**Details:**`);
      lines.push('```');
      lines.push(check.details);
      lines.push('```');
    }
    
    lines.push('');
    checkNumber++;
  }
  
  return lines.join('\n');
}

/**
 * Generate APPROVAL.md document
 */
export function generateApprovalDoc(): string {
  const lines: string[] = [];
  
  lines.push('# APPROVAL DOCUMENT — Studio Suno Package Validate');
  lines.push('');
  lines.push('## Purpose');
  lines.push('');
  lines.push('This tool validates Suno job packages created by `suno-package-prep` before Studio spends browser time.');
  lines.push('');
  lines.push('## What This Tool Does');
  lines.push('');
  lines.push('✅ **Validates offline** - No Suno API calls');
  lines.push('✅ **Read-only** - Never modifies job folders');
  lines.push('✅ **Safety checks** - PII detection, required files, metadata shape');
  lines.push('✅ **Preflight validation** - Catch issues before Chrome/Suno paste workflow');
  lines.push('');
  lines.push('## What This Tool Does NOT Do');
  lines.push('');
  lines.push('❌ No Suno API calls (official or unofficial)');
  lines.push('❌ No YouTube API calls');
  lines.push('❌ No browser automation');
  lines.push('❌ No auto-send of any kind');
  lines.push('❌ No file modifications');
  lines.push('');
  lines.push('## Validation Gates');
  lines.push('');
  lines.push('1. **Required Files Present** - lyrics.cleaned.txt, checklist.md, manifest.json');
  lines.push('2. **Metadata JSON Shape** - Valid metadata structure in manifest.json');
  lines.push('3. **Lyrics Not Empty** - Non-whitespace content in lyrics file');
  lines.push('4. **No PII Patterns** - No email addresses or phone numbers in lyrics');
  lines.push('5. **Manual Paste Checklist** - Checklist mentions manual workflow only');
  lines.push('');
  lines.push('## Studio Workflow');
  lines.push('');
  lines.push('```');
  lines.push('1. suno-package-prep creates job folder');
  lines.push('2. studio-suno-package-validate validates folder (THIS TOOL)');
  lines.push('3. Review report.md for pass/fail');
  lines.push('4. If passed: proceed with manual Chrome/Suno paste');
  lines.push('5. If failed: fix issues and re-validate');
  lines.push('```');
  lines.push('');
  lines.push('## Ownership');
  lines.push('');
  lines.push('- **Studio** owns the manual Chrome/Suno paste workflow');
  lines.push('- **Studio** owns when to generate Suno songs');
  lines.push('- **Studio** owns what happens with generated songs');
  lines.push('- This tool only validates job package quality');
  lines.push('');
  lines.push('## No Suno API / No Auto YouTube');
  lines.push('');
  lines.push('This tool is part of the **manual paste workflow** only.');
  lines.push('');
  lines.push('- ❌ No Suno API calls');
  lines.push('- ❌ No YouTube upload automation');
  lines.push('- ✅ Manual Chrome paste is the only approved workflow');
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('**Generated by:** studio-suno-package-validate');
  lines.push(`**Timestamp:** ${new Date().toISOString()}`);
  
  return lines.join('\n');
}

/**
 * Generate manifest.json
 */
export function generateManifest(report: ValidationReport, outdir: string): object {
  return {
    tool: 'studio-suno-package-validate',
    version: '1.0.0',
    generated_at: report.timestamp,
    job_dir: report.job_dir,
    output_dir: outdir,
    validation_result: {
      all_passed: report.summary.all_passed,
      passed: report.summary.passed,
      failed: report.summary.failed,
      total: report.summary.total_checks
    },
    outputs: {
      report_json: 'report.json',
      report_md: 'report.md',
      approval_md: 'APPROVAL.md',
      manifest_json: 'manifest.json'
    }
  };
}

/**
 * Write all output files
 */
export async function writeReports(
  report: ValidationReport,
  outdir: string
): Promise<void> {
  // Ensure output directory exists
  if (!fs.existsSync(outdir)) {
    fs.mkdirSync(outdir, { recursive: true });
  }
  
  // Write report.json
  fs.writeFileSync(
    path.join(outdir, 'report.json'),
    JSON.stringify(report, null, 2)
  );
  
  // Write report.md
  const markdown = generateMarkdownReport(report);
  fs.writeFileSync(
    path.join(outdir, 'report.md'),
    markdown
  );
  
  // Write APPROVAL.md
  const approval = generateApprovalDoc();
  fs.writeFileSync(
    path.join(outdir, 'APPROVAL.md'),
    approval
  );
  
  // Write manifest.json
  const manifest = generateManifest(report, outdir);
  fs.writeFileSync(
    path.join(outdir, 'manifest.json'),
    JSON.stringify(manifest, null, 2)
  );
}
