/**
 * Pack download utilities
 * Handles downloading generated packs as zip files for SA Ops
 */

export interface PackFile {
  [filename: string]: string
}

export interface PackResponse {
  packName: string
  timestamp: string
  cliCommand: string
  files: PackFile
}

/**
 * Download pack files as a zip
 * Note: This creates individual downloads for now since we don't have a zip library
 * SA Ops can create the folder structure manually
 */
export async function downloadPackAsZip(pack: PackResponse) {
  // For now, download each file individually
  // In production, we'd use JSZip or similar to create a proper zip
  
  const folder = pack.packName
  
  // Download each file
  Object.entries(pack.files).forEach(([filename, content]) => {
    const blob = new Blob([content], { 
      type: filename.endsWith('.json') ? 'application/json' : 'text/markdown'
    })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${folder}__${filename}` // Use __ separator for folder indication
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  })
  
  // Also download CLI command as shell script
  downloadCliScript(pack.packName, pack.cliCommand)
}

/**
 * Download CLI command as a shell script
 */
export function downloadCliScript(packName: string, cliCommand: string) {
  const scriptContent = `#!/bin/bash
# Generated by GuestFlow for ${packName}
# SA Ops CLI command for browns-* tools

${cliCommand}
`
  
  const blob = new Blob([scriptContent], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${packName}__RUN.sh`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

/**
 * Download all files in a single bundled markdown file for quick review
 */
export function downloadPackAsBundle(pack: PackResponse) {
  const lines: string[] = []
  
  lines.push(`# ${pack.packName}`)
  lines.push('')
  lines.push(`Generated: ${pack.timestamp}`)
  lines.push('')
  lines.push('---')
  lines.push('')
  
  // Add CLI command section
  lines.push('## CLI Command (SA Ops)')
  lines.push('')
  lines.push('```bash')
  lines.push(pack.cliCommand)
  lines.push('```')
  lines.push('')
  lines.push('---')
  lines.push('')
  
  // Add each file as a section
  Object.entries(pack.files).forEach(([filename, content]) => {
    lines.push(`## File: ${filename}`)
    lines.push('')
    lines.push('```')
    lines.push(content)
    lines.push('```')
    lines.push('')
    lines.push('---')
    lines.push('')
  })
  
  const bundleContent = lines.join('\n')
  const blob = new Blob([bundleContent], { type: 'text/markdown' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${pack.packName}__BUNDLE.md`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

/**
 * Copy CLI command to clipboard
 */
export async function copyCliCommand(cliCommand: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(cliCommand)
    return true
  } catch (err) {
    console.error('Failed to copy CLI command:', err)
    return false
  }
}
