import * as fs from 'fs';
import * as path from 'path';
import { MerchantGroup, QueueOutput, ManifestOutput } from './types.js';

export function writeQueueJson(
  outdir: string,
  merchants: MerchantGroup[],
  totalRows: number,
  totalUnmatched: number
): string {
  const outputPath = path.join(outdir, 'queue.json');

  const output: QueueOutput = {
    merchants,
    totalRows,
    totalUnmatched,
    generatedAt: new Date().toISOString(),
  };

  fs.writeFileSync(outputPath, JSON.stringify(output, null, 2), 'utf-8');
  return outputPath;
}

export function writeQueueMd(
  outdir: string,
  merchants: MerchantGroup[]
): string {
  const outputPath = path.join(outdir, 'queue.md');

  let content = '# Merchant Research Queue\n\n';
  content +=
    'Research the following merchants to determine their category and matching rules.\n\n';
  content += '**IMPORTANT:** Amounts are intentionally omitted from this list. ';
  content += 'Refer to queue.json for sample row references if needed.\n\n';
  content += '---\n\n';

  merchants.forEach((merchant, idx) => {
    content += `## ${idx + 1}. ${merchant.displayName}\n\n`;
    content += `- **Count:** ${merchant.count} transaction(s)\n`;

    if (merchant.firstDate && merchant.lastDate) {
      content += `- **Date range:** ${merchant.firstDate} to ${merchant.lastDate}\n`;
    } else if (merchant.firstDate) {
      content += `- **Date:** ${merchant.firstDate}\n`;
    }

    content += '\n**Known hints:** _(empty - awaiting research)_\n\n';
    content += '---\n\n';
  });

  fs.writeFileSync(outputPath, content, 'utf-8');
  return outputPath;
}

export function writeMissingFields(
  outdir: string,
  issues: string[],
  hasStatusColumn: boolean,
  hasDateColumn: boolean
): string {
  const outputPath = path.join(outdir, 'missing-fields.md');

  let content = '# Missing Fields Report\n\n';

  if (issues.length === 0 && hasStatusColumn && hasDateColumn) {
    content += '✅ No issues detected.\n\n';
    content += 'All rows have:\n';
    content += '- Valid merchant values\n';
    content += '- Status column present\n';
    content += '- Date column detected\n';
  } else {
    content += '⚠️ Issues detected during parsing:\n\n';

    if (!hasStatusColumn) {
      content += '### Status Column Missing\n\n';
      content +=
        'No status column was detected or provided. All rows are treated as unmatched.\n\n';
    }

    if (!hasDateColumn) {
      content += '### Date Column Missing\n\n';
      content +=
        'No date column was automatically detected. Date range tracking is disabled.\n\n';
    }

    if (issues.length > 0) {
      content += '### Row-level Issues\n\n';
      issues.forEach(issue => {
        content += `- ${issue}\n`;
      });
      content += '\n';
    }
  }

  fs.writeFileSync(outputPath, content, 'utf-8');
  return outputPath;
}

export function writeApproval(outdir: string): string {
  const outputPath = path.join(outdir, 'APPROVAL.md');

  const content = `# APPROVAL REQUIRED

## Purpose
This queue is a **research aid only**. Ledger owns manual Google Sheet updates.

## Scope
- ✅ Research unmatched merchants
- ✅ Identify categories and matching rules
- ✅ Update merchant knowledge base

## Out of Scope
- ❌ No automatic sheet writes
- ❌ No payment processing
- ❌ No bank API calls
- ❌ No auto-categorization

## Approval Gates
- **S1:** Ledger research using public sources only
- **H2:** Required before any sheet write or rule changes

## Next Steps
1. Review queue.md for merchant list
2. Research each merchant (web search, transaction patterns)
3. Document findings in merchant knowledge base
4. Update matching rules manually
5. Get H2 approval before applying sheet changes

---

**Generated by:** ledger-unmatched-merchant-queue  
**Date:** ${new Date().toISOString()}
`;

  fs.writeFileSync(outputPath, content, 'utf-8');
  return outputPath;
}

export function writeManifest(
  outdir: string,
  inputFile: string,
  outputFiles: string[],
  totalRows: number,
  totalUnmatched: number,
  uniqueMerchants: number
): string {
  const outputPath = path.join(outdir, 'manifest.json');

  const manifest: ManifestOutput = {
    tool: 'ledger-unmatched-merchant-queue',
    version: '1.0.0',
    generatedAt: new Date().toISOString(),
    input: inputFile,
    outputFiles: outputFiles.map(f => path.basename(f)),
    stats: {
      totalRows,
      totalUnmatched,
      uniqueMerchants,
    },
  };

  fs.writeFileSync(outputPath, JSON.stringify(manifest, null, 2), 'utf-8');
  return outputPath;
}
