#!/usr/bin/env python3
"""
drive-pdf-upload-prep: Offline PDF prep for Google Drive MCP upload

Prepares PDF files for Google Drive MCP create_file by converting them to
base64-encoded JSON payloads. Auto-compresses PDFs exceeding size limits.
"""

import argparse
import base64
import json
import os
import subprocess
import sys
from pathlib import Path
from typing import Dict, List, Optional


def get_pdf_size_kb(pdf_path: Path) -> float:
    """Get PDF file size in KB."""
    return pdf_path.stat().st_size / 1024


def pdf_to_base64(pdf_path: Path) -> str:
    """Convert PDF to base64 string."""
    with open(pdf_path, 'rb') as f:
        return base64.b64encode(f.read()).decode('utf-8')


def compress_pdf_ghostscript(input_path: Path, output_path: Path) -> bool:
    """
    Compress PDF using ghostscript with greyscale and image downsampling.
    Returns True if successful.
    """
    try:
        cmd = [
            'gs',
            '-sDEVICE=pdfwrite',
            '-dCompatibilityLevel=1.4',
            '-dPDFSETTINGS=/ebook',  # Medium quality
            '-dNOPAUSE',
            '-dQUIET',
            '-dBATCH',
            '-dColorConversionStrategy=/Gray',
            '-dProcessColorModel=/DeviceGray',
            f'-sOutputFile={output_path}',
            str(input_path)
        ]
        subprocess.run(cmd, check=True, capture_output=True)
        return True
    except (subprocess.CalledProcessError, FileNotFoundError) as e:
        print(f"Warning: ghostscript compression failed for {input_path.name}: {e}", file=sys.stderr)
        return False


def compress_pdf_raster(input_path: Path, output_path: Path, dpi: int = 150) -> bool:
    """
    Compress PDF by rasterizing pages to greyscale JPEG then rewrapping as PDF.
    Falls back to pillow+img2pdf if pdftoppm is unavailable.
    Returns True if successful.
    """
    try:
        # Try pdftoppm + img2pdf workflow
        import img2pdf
        from PIL import Image
        
        temp_dir = output_path.parent / f"_temp_{input_path.stem}"
        temp_dir.mkdir(exist_ok=True)
        
        try:
            # Convert PDF pages to PPM images
            subprocess.run([
                'pdftoppm',
                '-gray',
                '-r', str(dpi),
                str(input_path),
                str(temp_dir / 'page')
            ], check=True, capture_output=True)
            
            # Find generated images
            image_files = sorted(temp_dir.glob('page-*.pgm'))
            if not image_files:
                image_files = sorted(temp_dir.glob('page-*.ppm'))
            
            if not image_files:
                raise RuntimeError("No images generated by pdftoppm")
            
            # Convert to JPEG with compression
            jpeg_files = []
            for img_path in image_files:
                img = Image.open(img_path).convert('L')  # Greyscale
                jpeg_path = img_path.with_suffix('.jpg')
                img.save(jpeg_path, 'JPEG', quality=85, optimize=True)
                jpeg_files.append(jpeg_path)
            
            # Wrap JPEGs back into PDF
            with open(output_path, 'wb') as f:
                f.write(img2pdf.convert([str(p) for p in jpeg_files]))
            
            return True
            
        finally:
            # Cleanup temp files
            if temp_dir.exists():
                for f in temp_dir.glob('*'):
                    f.unlink()
                temp_dir.rmdir()
    
    except Exception as e:
        print(f"Warning: raster compression failed for {input_path.name}: {e}", file=sys.stderr)
        return False


def compress_pdf_iterative(input_path: Path, output_path: Path, max_b64_bytes: int) -> tuple[bool, Optional[int], Optional[int]]:
    """
    Attempt to compress PDF below max_b64_bytes threshold.
    Returns (success, original_bytes, compressed_bytes).
    """
    original_b64 = pdf_to_base64(input_path)
    original_size = len(original_b64)
    
    if original_size <= max_b64_bytes:
        return False, original_size, None  # No compression needed
    
    # Try ghostscript first (faster, preserves vector quality)
    temp_gs = output_path.parent / f"_temp_gs_{input_path.name}"
    if compress_pdf_ghostscript(input_path, temp_gs):
        gs_b64 = pdf_to_base64(temp_gs)
        if len(gs_b64) <= max_b64_bytes:
            temp_gs.rename(output_path)
            return True, original_size, len(gs_b64)
        temp_gs.unlink()
    
    # Fall back to raster compression with progressive DPI reduction
    for dpi in [150, 120, 96, 72]:
        temp_raster = output_path.parent / f"_temp_raster_{dpi}_{input_path.name}"
        if compress_pdf_raster(input_path, temp_raster, dpi=dpi):
            raster_b64 = pdf_to_base64(temp_raster)
            if len(raster_b64) <= max_b64_bytes:
                temp_raster.rename(output_path)
                return True, original_size, len(raster_b64)
            temp_raster.unlink()
    
    return False, original_size, None  # Compression failed


def process_pdf(pdf_path: Path, parent_id: str, max_b64_bytes: int, output_dir: Path) -> Dict:
    """
    Process a single PDF file and return metadata.
    Writes JSON payload to output_dir.
    """
    original_size = get_pdf_size_kb(pdf_path)
    compressed = False
    compression_note = None
    
    # Check if compression is needed
    original_b64 = pdf_to_base64(pdf_path)
    original_b64_size = len(original_b64)
    
    if original_b64_size > max_b64_bytes:
        # Attempt compression
        compressed_path = output_dir / f"compressed_{pdf_path.name}"
        success, orig_bytes, comp_bytes = compress_pdf_iterative(pdf_path, compressed_path, max_b64_bytes)
        
        if success:
            compressed = True
            final_b64 = pdf_to_base64(compressed_path)
            compression_note = f"Compressed from {orig_bytes} to {comp_bytes} bytes"
            compressed_path.unlink()  # Clean up intermediate file
        else:
            # Use original even if oversized (let user know)
            final_b64 = original_b64
            compression_note = f"Failed to compress below {max_b64_bytes} bytes (still {original_b64_size} bytes)"
    else:
        final_b64 = original_b64
    
    # Generate Drive create_file payload
    json_filename = pdf_path.stem + '.json'
    payload = {
        "title": pdf_path.name,
        "parentId": parent_id,
        "contentMimeType": "application/pdf",
        "disableConversionToGoogleType": True,
        "base64Content": final_b64
    }
    
    json_path = output_dir / json_filename
    with open(json_path, 'w') as f:
        json.dump(payload, f, indent=2)
    
    # Return metadata for manifest
    metadata = {
        "source_file": str(pdf_path.name),
        "json_output": json_filename,
        "original_kb": round(original_size, 2),
        "original_b64_bytes": original_b64_size,
        "final_b64_bytes": len(final_b64),
        "compressed": compressed
    }
    
    if compression_note:
        metadata["compression_note"] = compression_note
    
    return metadata


def main():
    parser = argparse.ArgumentParser(
        description='Prepare PDF files for Google Drive MCP create_file upload',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Process all PDFs in a directory
  %(prog)s --input-dir invoices/ --parent-id 1A2B3C4D --output-dir out/

  # Process specific PDFs with custom size limit
  %(prog)s --input-files invoice1.pdf invoice2.pdf --parent-id 1A2B3C --max-b64 12000 --output-dir out/

  # Use glob pattern
  %(prog)s --input-dir invoices/*.pdf --parent-id 1A2B3C --output-dir out/
"""
    )
    
    input_group = parser.add_mutually_exclusive_group(required=True)
    input_group.add_argument('--input-dir', type=str, help='Directory containing PDF files')
    input_group.add_argument('--input-files', nargs='+', type=str, help='Specific PDF files to process')
    
    parser.add_argument('--parent-id', type=str, required=True,
                        help='Google Drive folder ID (required for create_file)')
    parser.add_argument('--max-b64', type=int, default=15500,
                        help='Maximum base64 payload size in bytes (default: 15500)')
    parser.add_argument('--output-dir', type=str, default='out',
                        help='Output directory for JSON files (default: out/)')
    
    args = parser.parse_args()
    
    # Collect PDF files
    pdf_files: List[Path] = []
    
    if args.input_dir:
        input_path = Path(args.input_dir)
        if input_path.is_dir():
            pdf_files = list(input_path.glob('*.pdf'))
        else:
            # Try as glob pattern
            pdf_files = list(Path('.').glob(args.input_dir))
    else:
        pdf_files = [Path(f) for f in args.input_files]
    
    pdf_files = [f for f in pdf_files if f.is_file() and f.suffix.lower() == '.pdf']
    
    if not pdf_files:
        print("Error: No PDF files found", file=sys.stderr)
        sys.exit(1)
    
    # Create output directory
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    print(f"Processing {len(pdf_files)} PDF file(s)...")
    print(f"Parent ID: {args.parent_id}")
    print(f"Max base64 size: {args.max_b64} bytes")
    print(f"Output directory: {output_dir}")
    print()
    
    # Process each PDF
    manifest_entries = []
    for pdf_path in pdf_files:
        print(f"Processing {pdf_path.name}...", end=' ')
        try:
            metadata = process_pdf(pdf_path, args.parent_id, args.max_b64, output_dir)
            manifest_entries.append(metadata)
            
            status = "✓ compressed" if metadata['compressed'] else "✓ ok"
            print(status)
            
            if 'compression_note' in metadata:
                print(f"  → {metadata['compression_note']}")
        
        except Exception as e:
            print(f"✗ failed: {e}", file=sys.stderr)
            manifest_entries.append({
                "source_file": str(pdf_path.name),
                "error": str(e)
            })
    
    # Write manifest
    manifest = {
        "parent_id": args.parent_id,
        "max_b64_bytes": args.max_b64,
        "processed_count": len(pdf_files),
        "files": manifest_entries
    }
    
    manifest_path = output_dir / 'manifest.json'
    with open(manifest_path, 'w') as f:
        json.dump(manifest, f, indent=2)
    
    print()
    print(f"✓ Complete! Generated {len(manifest_entries)} JSON file(s)")
    print(f"  Manifest: {manifest_path}")
    print()
    print("Next steps:")
    print("  1. Review manifest.json for any compression failures")
    print("  2. Use hospitality Google-drive MCP 'create_file' with each JSON")
    print("  3. Pass JSON content as arguments to create_file (one at a time)")


if __name__ == '__main__':
    main()
