import { ProfileConfig, Profile } from './types.js';

export const PROFILES: Record<Profile, ProfileConfig> = {
  generic: {
    name: 'generic',
    dateAliases: ['date', 'transaction date', 'trans date', 'posting date', 'value date'],
    referenceAliases: ['reference', 'ref', 'transaction reference', 'trans ref', 'cheque number', 'cheque no', 'trace number', 'transaction id', 'trans id'],
    amountAliases: ['amount', 'transaction amount', 'trans amount', 'value'],
    debitAliases: ['debit', 'debit amount', 'withdrawal', 'withdrawals'],
    creditAliases: ['credit', 'credit amount', 'deposit', 'deposits'],
    descriptionAliases: ['description', 'details', 'transaction details', 'trans details', 'narrative', 'particulars'],
    payeeAliases: ['payee', 'beneficiary', 'recipient', 'merchant'],
    storeAliases: ['store', 'location', 'branch'],
  },
  fnb: {
    name: 'fnb',
    dateAliases: ['date', 'transaction date', 'trans date', 'posting date'],
    referenceAliases: ['reference', 'ref', 'transaction reference'],
    amountAliases: ['amount', 'transaction amount'],
    debitAliases: ['debit', 'debit amount'],
    creditAliases: ['credit', 'credit amount'],
    descriptionAliases: ['description', 'details', 'narrative'],
    payeeAliases: ['payee', 'beneficiary'],
    storeAliases: ['store', 'branch'],
  },
  standard: {
    name: 'standard',
    dateAliases: ['date', 'posting date', 'transaction date'],
    referenceAliases: ['reference', 'ref', 'cheque number'],
    amountAliases: ['amount', 'value'],
    debitAliases: ['debit', 'withdrawal'],
    creditAliases: ['credit', 'deposit'],
    descriptionAliases: ['description', 'particulars', 'details'],
    payeeAliases: ['payee', 'recipient'],
    storeAliases: ['store', 'location'],
  },
  absa: {
    name: 'absa',
    dateAliases: ['date', 'transaction date', 'value date'],
    referenceAliases: ['reference', 'ref', 'transaction reference'],
    amountAliases: ['amount', 'transaction amount'],
    debitAliases: ['debit', 'debit amount'],
    creditAliases: ['credit', 'credit amount'],
    descriptionAliases: ['description', 'narrative'],
    payeeAliases: ['payee', 'beneficiary'],
    storeAliases: ['store', 'branch'],
  },
  nedbank: {
    name: 'nedbank',
    dateAliases: ['date', 'transaction date', 'posting date'],
    referenceAliases: ['reference', 'ref', 'trace number'],
    amountAliases: ['amount', 'value'],
    debitAliases: ['debit', 'withdrawal'],
    creditAliases: ['credit', 'deposit'],
    descriptionAliases: ['description', 'details'],
    payeeAliases: ['payee', 'recipient'],
    storeAliases: ['store', 'location'],
  },
  payfast: {
    name: 'payfast',
    dateAliases: ['date', 'settlement date', 'transaction date', 'payment date'],
    referenceAliases: ['reference', 'payment reference', 'transaction id', 'pf_payment_id'],
    amountAliases: ['amount', 'net amount', 'settlement amount', 'gross'],
    debitAliases: ['fee', 'fees'],
    creditAliases: ['amount', 'gross', 'settlement amount'],
    descriptionAliases: ['description', 'item name', 'name_first', 'name_last', 'merchant'],
    payeeAliases: ['merchant', 'payee', 'name_first', 'name_last'],
    storeAliases: ['store', 'merchant'],
  },
  yoco: {
    name: 'yoco',
    dateAliases: ['date', 'settlement date', 'transaction date', 'created at'],
    referenceAliases: ['reference', 'receipt', 'receipt number', 'transaction id', 'yoco reference'],
    amountAliases: ['amount', 'net amount', 'settlement amount'],
    debitAliases: ['fee', 'fees'],
    creditAliases: ['amount', 'gross amount', 'settlement amount'],
    descriptionAliases: ['description', 'merchant', 'type'],
    payeeAliases: ['merchant', 'payee', 'customer'],
    storeAliases: ['store', 'location', 'merchant'],
  },
  'xero-import': {
    name: 'xero-import',
    dateAliases: ['date'],
    referenceAliases: ['reference'],
    amountAliases: ['amount'],
    debitAliases: [],
    creditAliases: [],
    descriptionAliases: ['description'],
    payeeAliases: ['payee'],
    storeAliases: ['store'],
  },
  auto: {
    name: 'auto',
    dateAliases: ['date', 'transaction date', 'trans date', 'posting date', 'value date', 'settlement date', 'payment date', 'created at'],
    referenceAliases: ['reference', 'ref', 'transaction reference', 'trans ref', 'cheque number', 'cheque no', 'trace number', 'transaction id', 'trans id', 'receipt', 'receipt number', 'yoco reference', 'pf_payment_id', 'payment reference'],
    amountAliases: ['amount', 'transaction amount', 'trans amount', 'value', 'net amount', 'settlement amount', 'gross', 'gross amount'],
    debitAliases: ['debit', 'debit amount', 'withdrawal', 'withdrawals', 'fee', 'fees'],
    creditAliases: ['credit', 'credit amount', 'deposit', 'deposits'],
    descriptionAliases: ['description', 'details', 'transaction details', 'trans details', 'narrative', 'particulars', 'item name', 'name_first', 'name_last', 'merchant', 'type'],
    payeeAliases: ['payee', 'beneficiary', 'recipient', 'merchant', 'name_first', 'name_last', 'customer'],
    storeAliases: ['store', 'location', 'branch', 'merchant'],
  },
};

export function getProfile(profileName: Profile): ProfileConfig {
  return PROFILES[profileName];
}
